all: provaPipe pipe-newSenzaClose pipe-newGenerico1 pipe-newGenerico2 partec190201 partec191201-a partec191201-b

provaPipe:
	gcc provaPipe.c -o provaPipe

pipe-newSenzaClose:
	gcc pipe-newSenzaClose.c -o pipe-newSenzaClose

pipe-newGenerico1:
	gcc pipe-newGenerico1.c -o newGenerico1

pipe-newGenerico2:
	gcc pipe-newGenerico2.c -o pipe-newGenerico2

partec190201:
	gcc partec190201.c -o partec190201

partec191201-a:
	gcc partec191201-a.c -o partec191201-a

partec191201-b:
	gcc partec191201-b.c -o partec191201

clean:
	rm provaPipe pipe-newSenzaClose pipe-newGenerico1 pipe-newGenerico2 partec190201 partec191201-a partec191201-b
