all: provaPipe pipe-newSenzaClose pipe-newGenerico1 pipe-newGenerico2 partec190201 partec191201-a partec191201-b

provaPipe: provaPipe.c
	gcc provaPipe.c -o provaPipe

pipe-newSenzaClose: pipe-newSenzaClose.c
	gcc pipe-newSenzaClose.c -o pipe-newSenzaClose

pipe-newGenerico1: pipe-newGenerico1.c
	gcc pipe-newGenerico1.c -o pipe-newGenerico1

pipe-newGenerico2: pipe-newGenerico2.c
	gcc pipe-newGenerico2.c -o pipe-newGenerico2

partec190201: partec190201.c
	gcc partec190201.c -o partec190201

partec191201-a: partec191201-a.c
	gcc partec191201-a.c -o partec191201-a

partec191201-b: partec191201-b.c
	gcc partec191201-b.c -o partec191201-b

clean:
	rm provaPipe pipe-newSenzaClose pipe-newGenerico1 pipe-newGenerico2 partec190201 partec191201-a partec191201-b
